[general]
live_config_reload = true

[font]
normal = { family = "GoMono Nerd Font Mono", style = "Regular" }
size = 12

[selection]
save_to_clipboard = true

[keyboard]
bindings = [{ key = "v", mods = "Control", action = "Paste" }]

# [terminal]
# [terminal.shell]
# args = ["--cd ~"]
# program = "wsl"
